// Code generated by ent, DO NOT EDIT.

package chargecommandhistory

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the chargecommandhistory type in the database.
	Label = "charge_command_history"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldVin holds the string denoting the vin field in the database.
	FieldVin = "vin"
	// FieldOperation holds the string denoting the operation field in the database.
	FieldOperation = "operation"
	// FieldAmps holds the string denoting the amps field in the database.
	FieldAmps = "amps"
	// FieldTimestamp holds the string denoting the timestamp field in the database.
	FieldTimestamp = "timestamp"
	// Table holds the table name of the chargecommandhistory in the database.
	Table = "charge_command_histories"
)

// Columns holds all SQL columns for chargecommandhistory fields.
var Columns = []string{
	FieldID,
	FieldVin,
	FieldOperation,
	FieldAmps,
	FieldTimestamp,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the ChargeCommandHistory queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByVin orders the results by the vin field.
func ByVin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVin, opts...).ToFunc()
}

// ByOperation orders the results by the operation field.
func ByOperation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperation, opts...).ToFunc()
}

// ByAmps orders the results by the amps field.
func ByAmps(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmps, opts...).ToFunc()
}

// ByTimestamp orders the results by the timestamp field.
func ByTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimestamp, opts...).ToFunc()
}
