// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"

	"github.com/sawadashota/tesla-home-powerflow-optimizer/ent/chargestatecache"
	"github.com/sawadashota/tesla-home-powerflow-optimizer/ent/predicate"
)

// ChargeStateCacheQuery is the builder for querying ChargeStateCache entities.
type ChargeStateCacheQuery struct {
	config
	ctx        *QueryContext
	order      []chargestatecache.OrderOption
	inters     []Interceptor
	predicates []predicate.ChargeStateCache
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChargeStateCacheQuery builder.
func (cscq *ChargeStateCacheQuery) Where(ps ...predicate.ChargeStateCache) *ChargeStateCacheQuery {
	cscq.predicates = append(cscq.predicates, ps...)
	return cscq
}

// Limit the number of records to be returned by this query.
func (cscq *ChargeStateCacheQuery) Limit(limit int) *ChargeStateCacheQuery {
	cscq.ctx.Limit = &limit
	return cscq
}

// Offset to start from.
func (cscq *ChargeStateCacheQuery) Offset(offset int) *ChargeStateCacheQuery {
	cscq.ctx.Offset = &offset
	return cscq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cscq *ChargeStateCacheQuery) Unique(unique bool) *ChargeStateCacheQuery {
	cscq.ctx.Unique = &unique
	return cscq
}

// Order specifies how the records should be ordered.
func (cscq *ChargeStateCacheQuery) Order(o ...chargestatecache.OrderOption) *ChargeStateCacheQuery {
	cscq.order = append(cscq.order, o...)
	return cscq
}

// First returns the first ChargeStateCache entity from the query.
// Returns a *NotFoundError when no ChargeStateCache was found.
func (cscq *ChargeStateCacheQuery) First(ctx context.Context) (*ChargeStateCache, error) {
	nodes, err := cscq.Limit(1).All(setContextOp(ctx, cscq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{chargestatecache.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cscq *ChargeStateCacheQuery) FirstX(ctx context.Context) *ChargeStateCache {
	node, err := cscq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ChargeStateCache ID from the query.
// Returns a *NotFoundError when no ChargeStateCache ID was found.
func (cscq *ChargeStateCacheQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cscq.Limit(1).IDs(setContextOp(ctx, cscq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{chargestatecache.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cscq *ChargeStateCacheQuery) FirstIDX(ctx context.Context) int {
	id, err := cscq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ChargeStateCache entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ChargeStateCache entity is found.
// Returns a *NotFoundError when no ChargeStateCache entities are found.
func (cscq *ChargeStateCacheQuery) Only(ctx context.Context) (*ChargeStateCache, error) {
	nodes, err := cscq.Limit(2).All(setContextOp(ctx, cscq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{chargestatecache.Label}
	default:
		return nil, &NotSingularError{chargestatecache.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cscq *ChargeStateCacheQuery) OnlyX(ctx context.Context) *ChargeStateCache {
	node, err := cscq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ChargeStateCache ID in the query.
// Returns a *NotSingularError when more than one ChargeStateCache ID is found.
// Returns a *NotFoundError when no entities are found.
func (cscq *ChargeStateCacheQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cscq.Limit(2).IDs(setContextOp(ctx, cscq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{chargestatecache.Label}
	default:
		err = &NotSingularError{chargestatecache.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cscq *ChargeStateCacheQuery) OnlyIDX(ctx context.Context) int {
	id, err := cscq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ChargeStateCaches.
func (cscq *ChargeStateCacheQuery) All(ctx context.Context) ([]*ChargeStateCache, error) {
	ctx = setContextOp(ctx, cscq.ctx, ent.OpQueryAll)
	if err := cscq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ChargeStateCache, *ChargeStateCacheQuery]()
	return withInterceptors[[]*ChargeStateCache](ctx, cscq, qr, cscq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cscq *ChargeStateCacheQuery) AllX(ctx context.Context) []*ChargeStateCache {
	nodes, err := cscq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ChargeStateCache IDs.
func (cscq *ChargeStateCacheQuery) IDs(ctx context.Context) (ids []int, err error) {
	if cscq.ctx.Unique == nil && cscq.path != nil {
		cscq.Unique(true)
	}
	ctx = setContextOp(ctx, cscq.ctx, ent.OpQueryIDs)
	if err = cscq.Select(chargestatecache.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cscq *ChargeStateCacheQuery) IDsX(ctx context.Context) []int {
	ids, err := cscq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cscq *ChargeStateCacheQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cscq.ctx, ent.OpQueryCount)
	if err := cscq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cscq, querierCount[*ChargeStateCacheQuery](), cscq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cscq *ChargeStateCacheQuery) CountX(ctx context.Context) int {
	count, err := cscq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cscq *ChargeStateCacheQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cscq.ctx, ent.OpQueryExist)
	switch _, err := cscq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cscq *ChargeStateCacheQuery) ExistX(ctx context.Context) bool {
	exist, err := cscq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChargeStateCacheQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cscq *ChargeStateCacheQuery) Clone() *ChargeStateCacheQuery {
	if cscq == nil {
		return nil
	}
	return &ChargeStateCacheQuery{
		config:     cscq.config,
		ctx:        cscq.ctx.Clone(),
		order:      append([]chargestatecache.OrderOption{}, cscq.order...),
		inters:     append([]Interceptor{}, cscq.inters...),
		predicates: append([]predicate.ChargeStateCache{}, cscq.predicates...),
		// clone intermediate query.
		sql:  cscq.sql.Clone(),
		path: cscq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Vin string `json:"vin,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ChargeStateCache.Query().
//		GroupBy(chargestatecache.FieldVin).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cscq *ChargeStateCacheQuery) GroupBy(field string, fields ...string) *ChargeStateCacheGroupBy {
	cscq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChargeStateCacheGroupBy{build: cscq}
	grbuild.flds = &cscq.ctx.Fields
	grbuild.label = chargestatecache.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Vin string `json:"vin,omitempty"`
//	}
//
//	client.ChargeStateCache.Query().
//		Select(chargestatecache.FieldVin).
//		Scan(ctx, &v)
func (cscq *ChargeStateCacheQuery) Select(fields ...string) *ChargeStateCacheSelect {
	cscq.ctx.Fields = append(cscq.ctx.Fields, fields...)
	sbuild := &ChargeStateCacheSelect{ChargeStateCacheQuery: cscq}
	sbuild.label = chargestatecache.Label
	sbuild.flds, sbuild.scan = &cscq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChargeStateCacheSelect configured with the given aggregations.
func (cscq *ChargeStateCacheQuery) Aggregate(fns ...AggregateFunc) *ChargeStateCacheSelect {
	return cscq.Select().Aggregate(fns...)
}

func (cscq *ChargeStateCacheQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cscq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cscq); err != nil {
				return err
			}
		}
	}
	for _, f := range cscq.ctx.Fields {
		if !chargestatecache.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cscq.path != nil {
		prev, err := cscq.path(ctx)
		if err != nil {
			return err
		}
		cscq.sql = prev
	}
	return nil
}

func (cscq *ChargeStateCacheQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ChargeStateCache, error) {
	var (
		nodes = []*ChargeStateCache{}
		_spec = cscq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ChargeStateCache).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ChargeStateCache{config: cscq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cscq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (cscq *ChargeStateCacheQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cscq.querySpec()
	_spec.Node.Columns = cscq.ctx.Fields
	if len(cscq.ctx.Fields) > 0 {
		_spec.Unique = cscq.ctx.Unique != nil && *cscq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cscq.driver, _spec)
}

func (cscq *ChargeStateCacheQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(chargestatecache.Table, chargestatecache.Columns, sqlgraph.NewFieldSpec(chargestatecache.FieldID, field.TypeInt))
	_spec.From = cscq.sql
	if unique := cscq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cscq.path != nil {
		_spec.Unique = true
	}
	if fields := cscq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chargestatecache.FieldID)
		for i := range fields {
			if fields[i] != chargestatecache.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cscq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cscq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cscq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cscq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cscq *ChargeStateCacheQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cscq.driver.Dialect())
	t1 := builder.Table(chargestatecache.Table)
	columns := cscq.ctx.Fields
	if len(columns) == 0 {
		columns = chargestatecache.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cscq.sql != nil {
		selector = cscq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cscq.ctx.Unique != nil && *cscq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cscq.predicates {
		p(selector)
	}
	for _, p := range cscq.order {
		p(selector)
	}
	if offset := cscq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cscq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ChargeStateCacheGroupBy is the group-by builder for ChargeStateCache entities.
type ChargeStateCacheGroupBy struct {
	selector
	build *ChargeStateCacheQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cscgb *ChargeStateCacheGroupBy) Aggregate(fns ...AggregateFunc) *ChargeStateCacheGroupBy {
	cscgb.fns = append(cscgb.fns, fns...)
	return cscgb
}

// Scan applies the selector query and scans the result into the given value.
func (cscgb *ChargeStateCacheGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cscgb.build.ctx, ent.OpQueryGroupBy)
	if err := cscgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChargeStateCacheQuery, *ChargeStateCacheGroupBy](ctx, cscgb.build, cscgb, cscgb.build.inters, v)
}

func (cscgb *ChargeStateCacheGroupBy) sqlScan(ctx context.Context, root *ChargeStateCacheQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cscgb.fns))
	for _, fn := range cscgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cscgb.flds)+len(cscgb.fns))
		for _, f := range *cscgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cscgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cscgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChargeStateCacheSelect is the builder for selecting fields of ChargeStateCache entities.
type ChargeStateCacheSelect struct {
	*ChargeStateCacheQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cscs *ChargeStateCacheSelect) Aggregate(fns ...AggregateFunc) *ChargeStateCacheSelect {
	cscs.fns = append(cscs.fns, fns...)
	return cscs
}

// Scan applies the selector query and scans the result into the given value.
func (cscs *ChargeStateCacheSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cscs.ctx, ent.OpQuerySelect)
	if err := cscs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChargeStateCacheQuery, *ChargeStateCacheSelect](ctx, cscs.ChargeStateCacheQuery, cscs, cscs.inters, v)
}

func (cscs *ChargeStateCacheSelect) sqlScan(ctx context.Context, root *ChargeStateCacheQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cscs.fns))
	for _, fn := range cscs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cscs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cscs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
