// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"

	"github.com/sawadashota/tesla-home-powerflow-optimizer/ent/powermetric"
)

// PowerMetric is the model entity for the PowerMetric schema.
type PowerMetric struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Watt holds the value of the "watt" field.
	Watt int `json:"watt,omitempty"`
	// Timestamp holds the value of the "timestamp" field.
	Timestamp    time.Time `json:"timestamp,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PowerMetric) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case powermetric.FieldID, powermetric.FieldWatt:
			values[i] = new(sql.NullInt64)
		case powermetric.FieldName:
			values[i] = new(sql.NullString)
		case powermetric.FieldTimestamp:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PowerMetric fields.
func (pm *PowerMetric) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case powermetric.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pm.ID = int(value.Int64)
		case powermetric.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				pm.Name = value.String
			}
		case powermetric.FieldWatt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field watt", values[i])
			} else if value.Valid {
				pm.Watt = int(value.Int64)
			}
		case powermetric.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field timestamp", values[i])
			} else if value.Valid {
				pm.Timestamp = value.Time
			}
		default:
			pm.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PowerMetric.
// This includes values selected through modifiers, order, etc.
func (pm *PowerMetric) Value(name string) (ent.Value, error) {
	return pm.selectValues.Get(name)
}

// Update returns a builder for updating this PowerMetric.
// Note that you need to call PowerMetric.Unwrap() before calling this method if this PowerMetric
// was returned from a transaction, and the transaction was committed or rolled back.
func (pm *PowerMetric) Update() *PowerMetricUpdateOne {
	return NewPowerMetricClient(pm.config).UpdateOne(pm)
}

// Unwrap unwraps the PowerMetric entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pm *PowerMetric) Unwrap() *PowerMetric {
	_tx, ok := pm.config.driver.(*txDriver)
	if !ok {
		panic("ent: PowerMetric is not a transactional entity")
	}
	pm.config.driver = _tx.drv
	return pm
}

// String implements the fmt.Stringer.
func (pm *PowerMetric) String() string {
	var builder strings.Builder
	builder.WriteString("PowerMetric(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pm.ID))
	builder.WriteString("name=")
	builder.WriteString(pm.Name)
	builder.WriteString(", ")
	builder.WriteString("watt=")
	builder.WriteString(fmt.Sprintf("%v", pm.Watt))
	builder.WriteString(", ")
	builder.WriteString("timestamp=")
	builder.WriteString(pm.Timestamp.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PowerMetrics is a parsable slice of PowerMetric.
type PowerMetrics []*PowerMetric
